version: 2.1

jobs:
  build:
    environment:
      JOBS: 1 # https://github.com/emberjs/ember.js/issues/15641
    docker:
      - image: circleci/node:12.20.1-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "yarn.lock" }}
            - v2-dependencies-
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: v2-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn lint:js
      - run: COVERAGE=true yarn test && yarn codecov -f coverage/coverage-summary.json
